### ISSUE TITLE
Hologram bug

### ISSUE THREAD

**Issue by LuluxClient** [BG-Software-LLC/SSB-OneBlock#11]
### Minecraft's Version

This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)

### Plugin's Version

1.8.4.517

### Describe the bug

When stopping the server while a player is going under a new phase on oneblock the hologram won't disappears 

### To Reproduce

1. Break block until the countdown starts to go in a new phase
2. restart the server
3. join back and the countdown hologram is still here

### Additional Information

https://github.com/BG-Software-LLC/SSB-OneBlock/issues/7#issuecomment-1037257987

**Comment by iSeitan** [comment]
Stil having this issue

**Comment by OmerBenGera** [comment]
> Stil having this issue

Open a new issue, this one was opened a year ago
