### ISSUE TITLE
Block physics-listener bug

### ISSUE THREAD

**Issue by LuluxClient** [BG-Software-LLC/SSB-OneBlock#12]
### Minecraft's Version

This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)
You are running the latest version

### Plugin's Version

1.8.4.517

### Describe the bug

When having this option "physics-listener" on true gravel and more are still getting affected by gravity: https://gyazo.com/4e23805f5e47694a1dbb1a50bdeb3552

### To Reproduce

Go into phase 2 and mine the blocks until there is gravel blocks

### Additional Information

Java 17

**Comment by OmerBenGera** [comment]
This is not a bug. Also, `physics-listener` is not part of OneBlock.
