### ISSUE TITLE
Double upgrade

### ISSUE THREAD

**Issue by LuluxClient** [BG-Software-LLC/SSB-OneBlock#14]
### Minecraft's Version

This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)

### Plugin's Version

SuperiorSkyblock2 version 1.8.4.518

### Describe the bug

When going into the next phase I get upgraded twice, for example I'm on phase one and when I break the last block in order to go in phase 2 I will go directly to phase 3 as you can see in my chat: https://gyazo.com/62fb3a0461c363a2e14dce69c255556d and it's indeed phase 4 instead of being the phase 3. 

### To Reproduce

Break blocks until you go to the next phase and you will double upgrade and miss 1 phase.

**Comment by OmerBenGera** [comment]
Fixed in latest build
