### ISSUE TITLE
1.18.2 support

### ISSUE THREAD

**Issue by LuluxClient** [BG-Software-LLC/SSB-OneBlock#15]
### Minecraft's Version

1.18.2

### Plugin's Version

1.8.4b394

### Describe the bug

1.18.2 isn't supported

### To Reproduce

Be on 1.18.2 with pufferfish or another spigot

### Additional Information

Errors: https://pastebin.com/zcJR5Lgx

**Comment by OmerBenGera** [comment]
Right, 1.18.2 is not supported yet :)
I will add support next week hopefully.

**Comment by OmerBenGera** [comment]
Support was added in latest version of OneBlock :)
