### ISSUE TITLE
Island Level Issue

### ISSUE THREAD

**Issue by iAabes** [BG-Software-LLC/SSB-OneBlock#17]
### Minecraft's Version

1.18.1

### Plugin's Version

https://hub.bg-software.com/job/SuperiorSkyblock%20Addons/job/OneBlock/lastSuccessfulBuild/artifact/target/SSBOneBlock-1.2.0-b16.jar

### Describe the bug

When you mine a generated block (island phases) it contributes towards your island level, even if the block is no longer there

The island-level system thinks that those blocks you have mined are still there or something.

### To Reproduce

Have an option to enable /is recalc being automatically run whenever you want.

**Comment by OmerBenGera** [comment]
Should be fixed on latest dev build

**Comment by OmerBenGera** [comment]
Closing this for now
If the issue still persists, lmk
