### ISSUE TITLE
the addon is not compatible yet with 1.18.2

### ISSUE THREAD

**Issue by ItzFabb-uwu** [BG-Software-LLC/SSB-OneBlock#19]
### Minecraft's Version

This server is running Paper version git-Paper-"e7d928a" (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e7d928a)
You are 8 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-"91f3eda" (MC: 1.18.1)

### Plugin's Version

1.9.0 b576 SuperiorSkyblock2 | Plugin

SSBOneBlock-1.2.0-b11.jar

### Describe the bug

Throws an error whenever you started your server @: 1.18.2

### To Reproduce

put superiorskyblock2 and oneblock addon inside your server plugins (i know i know ssb oneblock is inside the modules!)

**Comment by OmerBenGera** [comment]
Update the addon to latest version

**Comment by ItzFabb-uwu** [comment]
okay fixed!
