### ISSUE TITLE
IllegalArgumentException onEnable()

### ISSUE THREAD

**Issue by MineTribes** [BG-Software-LLC/SSB-OneBlock#2]
**Steps to reproduce:**
1) Create a 1.17.1 server (I run Purpur build 1261, but it warns with any version/fork)
2) Boot up the server with SSB build 199 and SSB OneBlock build 2

**Issue:**
Spams the following warning:
https://pastebin.com/QN5ssspB

**Comment by OmerBenGera** [comment]
Update your files to meet the correct naming of entities in 1.16/1.17
