### ISSUE TITLE
Generator phase

### ISSUE THREAD

**Issue by xOpasik** [BG-Software-LLC/SSB-OneBlock#23]
### Minecraft's Version

1.17.1 purpur

### Plugin's Version

SuperiorSkyblock2-1.10.0.jar

SSBOneBlock-1.2.0-b6.jar

### Describe the bug

The progress of the generator phases resets each time the server is restarted, problems occur in both cases - Forced server shutdown and normal restart.
If, for example, someone had the 5th phase of the generator, then after restarting he receives 1 phase of the generator again

### To Reproduce

Restart the server

**Comment by OmerBenGera** [comment]
Update the module to latest dev build, let me know if it works for you.

**Comment by xOpasik** [comment]
Now the generator is not working at all

**Comment by xOpasik** [comment]
Okay, I changed something in my config and it's already working, but it still resets after a reboot

**Comment by OmerBenGera** [comment]
I just tried it myself and it works flawlessly fine for me.
Are you shutting your server using `/stop` or you just kill it out of nowhere?

**Comment by xOpasik** [comment]
![image](https://user-images.githubusercontent.com/105610066/170674196-7b1db731-19f3-44c0-8a85-ca97ec4362fb.png)

**Comment by xOpasik** [comment]
Restart server

**Comment by OmerBenGera** [comment]
Use /stop, then send me the logs of your server.

**Comment by xOpasik** [comment]
You have exceeded the maximum paste size of 512 kilobytes per paste. [PRO](https://pastebin.com/pro) users don't have this limit!

**Comment by xOpasik** [comment]
discord look

**Comment by OmerBenGera** [comment]
> You have exceeded the maximum paste size of 512 kilobytes per paste. [PRO](https://pastebin.com/pro) users don't have this limit!

Use another service then, such as hastebin or literally anything else and send it here

**Comment by xOpasik** [comment]
I checked 4 pages and it still goes

**Comment by xOpasik** [comment]
I tried and I can't add anywhere, take a look at the discord

**Comment by OmerBenGera** [comment]
Upload it to mediafire and send a link here

**Comment by xOpasik** [comment]
https://www.mediafire.com/file/156ci7go4zvidim/2022-05-27-3.log.gz/file

**Comment by xOpasik** [comment]
looked

**Comment by OmerBenGera** [comment]
> looked

There is no point in bumping the issue.
I will look into it when I have the time and report here with results.

**Comment by OmerBenGera** [comment]
Check out latest build, let me know if it's better.

**Comment by xOpasik** [comment]
**Describe the bug**
Earlier I reported that there was a problem with generator phases resetting after server restart. Generally, an unusual situation, their progress was reset, etc., they normally had to extract resources from phase 1, but some people have a higher level of the generator phase shown on the scoreboard than they currently have

**To Reproduce**
In fact, this error occurs only in people who still had the same island, if you delete it and recreate it correctly, everything is fine

**Additional Information**

![image](https://user-images.githubusercontent.com/105610066/172649232-5ab04f27-bcce-49a5-93bf-f02588eb16bf.png)


          - ' &#7CFC5A•&#C7C7C7 Poziom generatora: &#F8BE00%superior_oneblock_phase_level%'
          - ' &#7CFC5A•&#C7C7C7 Postęp: &#2AD5EF%superior_oneblock_progress%%'
          - '   &7[&r%progress_bar_{superior_oneblock_progress}_c:&#2AD5EF■_p:&#2AD5EF■_r:&7■_l:10_m:100_fullbar:&#00E10BOsiągnąłeś lvl UP!%&7]'

**Comment by OmerBenGera** [comment]
> **Describe the bug** Earlier I reported that there was a problem with generator phases resetting after server restart. Generally, an unusual situation, their progress was reset, etc., they normally had to extract resources from phase 1, but some people have a higher level of the generator phase shown on the scoreboard than they currently have
> 
> **To Reproduce** In fact, this error occurs only in people who still had the same island, if you delete it and recreate it correctly, everything is fine
> 
> **Additional Information**
> 
> ![image](https://user-images.githubusercontent.com/105610066/172649232-5ab04f27-bcce-49a5-93bf-f02588eb16bf.png)
> 
> ```
>       - ' &#7CFC5A•&#C7C7C7 Poziom generatora: &#F8BE00%superior_oneblock_phase_level%'
>       - ' &#7CFC5A•&#C7C7C7 Postęp: &#2AD5EF%superior_oneblock_progress%%'
>       - '   &7[&r%progress_bar_{superior_oneblock_progress}_c:&#2AD5EF■_p:&#2AD5EF■_r:&7■_l:10_m:100_fullbar:&#00E10BOsiągnąłeś lvl UP!%&7]'
> ```

I dont understand the issue.

**Comment by xOpasik** [comment]
Basically, I got help on discord and it works. To close
