### ISSUE TITLE
End-Phase

### ISSUE THREAD

**Issue by FrinshHD** [BG-Software-LLC/SSB-OneBlock#24]
### Minecraft's Version

When a user has ended the end phase nothing happens can i restart the process then maybee?

### Plugin's Version

latest

### Describe the bug

...

### To Reproduce

do what i said

**Comment by OmerBenGera** [comment]
Thats not a bug.
You are more than welcome to make any command get executed once people reach the end phase.
 In the default files, the end world is unlocked for the island.
