### ISSUE TITLE
Missions

### ISSUE THREAD

**Issue by xOpasik** [BG-Software-LLC/SSB-OneBlock#25]
### Minecraft's Version

the latest version + the latest version of the one block module

### Plugin's Version

the latest version + the latest version of the one block module

### Describe the bug

I noticed that I had set up
# Whether only naturally spawned blocks should be counted towards the mission or not.
only-natural-blocks: true

In missions -> the mining category does not include ores from the one block generator

This is the case with all ores -> I checked

### To Reproduce

I think it should work, because it will spawn "pseudo naturally -> from the generator"

### Additional Information

I have described above; Mr.

**Comment by OmerBenGera** [comment]
I dont understand what you're reporting here exactly.

**Comment by xOpasik** [comment]
![image](https://user-images.githubusercontent.com/105610066/171340129-1f1f2a68-4628-4447-a9ff-f8ad83492474.png)
![image](https://user-images.githubusercontent.com/105610066/171340168-e27a62a3-88ac-4630-bfe1-d43487501822.png)
![image](https://user-images.githubusercontent.com/105610066/171340201-a5ca9870-bcbf-4787-8b6b-224ba9443a55.png)

**Comment by xOpasik** [comment]
The point is, coal, iron, etc. blocks do not count when this option is turned on

**Comment by OmerBenGera** [comment]
> The point is, coal, iron, etc. blocks do not count when this option is turned on

Blocks of OneBlock?

**Comment by xOpasik** [comment]
I checked it basically only for the mining category, but maybe I do not fully catch it from other categories as well

**Comment by OmerBenGera** [comment]
Fixed in latest build
