### ISSUE TITLE
OneBlock

### ISSUE THREAD

**Issue by xOpasik** [BG-Software-LLC/SSB-OneBlock#26]
### Minecraft's Version

1.17.1 purpur

### Plugin's Version

newest

### Describe the bug

Hello, I tried to use
auto-language-detection: false
auto-language-detection: true

Unfortunately, none of the options gives results, and more specifically, if sand or gravel appears from the oneblock generator, etc., they immediately fall to nothingness, unless someone places a block under the generator

### To Reproduce

Extract resources from the generator -> sand / gravel and other such blocks

### Additional Information

In fact, if there was an option that "naturally from the generator, these" loose "blocks would not fly to nothingness, it would be great

**Comment by OmerBenGera** [comment]
About `auto-language-detection`, you must have ProtocolLib installed. Then, for new players, it will detect their language automatically and set it as their language, only if there is a valid translation available.

About send and gravel falling to void - intended - place a block below :)

**Comment by xOpasik** [comment]
Oh no przepraszam, złą rzecz skopiowałem xD

**Comment by xOpasik** [comment]
Oh sorry sorry i copied the wrong thing xD

**Comment by xOpasik** [comment]
About send and gravel falling to void - intended - place a block below :)
Okay, I get it cool
