### ISSUE TITLE
Phase generator oneblock

### ISSUE THREAD

**Issue by xOpasik** [BG-Software-LLC/SSB-OneBlock#30]
### Minecraft's Version

1.17.1

### Plugin's Version

newest

### Describe the bug

There are bugs that bugs the oneblock generator
Please add some debugging features of that something. I tried to change the generator phase person -> The change worked but it cannot destroy the block

### To Reproduce

-

### Additional Information

-

**Comment by OmerBenGera** [comment]
If you have a bug, report it.
