### ISSUE TITLE
OneBlock generator 

### ISSUE THREAD

**Issue by xOpasik** [BG-Software-LLC/SSB-OneBlock#31]
### Minecraft's Version

1.17.1

### Plugin's Version

Najnowsza

### Describe the bug

Four islands suddenly lost their ability to destroy the oneblock generator.

### To Reproduce

-

### Additional Information

My attempts to fix this:
I tried using pod / oneblock commands - I changed the phases of the generator and the block changed but it still could not be destroyed. When I tried to destroy it, nothing came out of it, and when I had an OP - all permissions, etc., no effect, the same was with gamemode creative. The only way out was // set 0 but after placing any block on this grid again it was "indestructible" again - There was a destruction animation, but it came back every time and nothing came out

**Comment by OmerBenGera** [comment]
What happens when you break it?
Any errors in console?

**Comment by xOpasik** [comment]
No messages in the process of destruction attempt

**Comment by xOpasik** [comment]
Mainly I care a little to try to restore this generator for them, because these people have already quite extensive islands; /

**Comment by xOpasik** [comment]
![image](https://user-images.githubusercontent.com/105610066/174018972-9e799100-1f00-4e95-8e4d-baf4ed7334f7.png)

I used the command, the phase itself changed but it was still impossible to destroy it

**Comment by OmerBenGera** [comment]
> ![image](https://user-images.githubusercontent.com/105610066/174018972-9e799100-1f00-4e95-8e4d-baf4ed7334f7.png)
> 
> I used the command, the phase itself changed but it was still impossible to destroy it

Take a video of the issue please.

**Comment by xOpasik** [comment]
https://www.youtube.com/watch?v=Mn-2Jiuwcxs

**Comment by xOpasik** [comment]
![image](https://user-images.githubusercontent.com/105610066/174252689-09b929a9-bed6-4f17-a541-b47c96fc0fc3.png)
Something is buggy, as if I'm added to his island and he gets all messages, but if he wants to leave, I can't. The problem is when I noticed that "when" I stomp on his island, the oneblock generator stops working, but after restart it works again hmm. Do you have any idea?

**Comment by xOpasik** [comment]
But when you do a restart, they have to get it from scratch each time

**Comment by xOpasik** [comment]
![image](https://user-images.githubusercontent.com/105610066/174253313-f6432076-8540-40d4-9750-0b2b0a963ac8.png)

**Comment by OmerBenGera** [comment]
> ![image](https://user-images.githubusercontent.com/105610066/174253313-f6432076-8540-40d4-9750-0b2b0a963ac8.png)

I don't think these warnings come from the oneblock module

**Comment by xOpasik** [comment]
Means this is an error that I mentioned that I am spiritually related to a certain island (all messages from it come to me when someone enters / reaches a new generator level etc.) And at the same time I can have my own island. Do you know how I can remove? I tried to get to her and leave / remove the administrative command, but to no avail

**Comment by OmerBenGera** [comment]
> Means this is an error that I mentioned that I am spiritually related to a certain island (all messages from it come to me when someone enters / reaches a new generator level etc.) And at the same time I can have my own island. Do you know how I can remove? I tried to get to her and leave / remove the administrative command, but to no avail

I don't understand what you want to do tbh.

**Comment by xOpasik** [comment]
Look at my files you will understand; v

**Comment by xOpasik** [comment]
And how?

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by xOpasik** [comment]
Unfortunately, I am not able to check it so far; d
