### ISSUE TITLE
Superiorblock2 - Border

### ISSUE THREAD

**Issue by xOpasik** [BG-Software-LLC/SSB-OneBlock#32]
### Minecraft's Version

1.17.1

### Plugin's Version

![image](https://user-images.githubusercontent.com/105610066/173806675-290d4608-1725-4091-a28d-e5fa70b07b98.png)

### Describe the bug

Island border is not displayed

### To Reproduce

-

### Additional Information

![image](https://user-images.githubusercontent.com/105610066/173806941-eeeec6ba-e236-474e-bd97-d6e2a778918a.png)

Something strange happened, I tried to remove the island / create from scratch and there was still no border, none of the players can see border now (it worked earlier)

I tried every option here and unfortunately it does not appear at all (I turned on / off the border) and restarted the server

**Comment by OmerBenGera** [comment]
Not related to OneBlock in any way.
