### ISSUE TITLE
Message bug

### ISSUE THREAD

**Issue by LuluxClient** [BG-Software-LLC/SSB-OneBlock#33]
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-71 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 671d68b on HEAD)
You are on the latest version!
Previous version: git-Pufferfish-70 (MC: 1.18.2)

### Plugin's Version

1.2.1-b27

### Describe the bug

Everyone can see the progress of your oneblock and the phase update message except the owner of the island even tho he is currently breaking the block and is on the island. 

### To Reproduce

Just have 2 people breaking the block, 1 being the island owner and the second one just a visitor

### Additional Information
On this gif my friend can see the update message and the progress in his action bar.
https://gyazo.com/3384ad01e30f917dcd79a41594e201ed

**Comment by LuluxClient** [comment]
Ill delete the oneblock addon and do a fresh config

**Comment by LuluxClient** [comment]
Also where could I disable that option since I can't find anything related to action bars in the configs ?

**Comment by OmerBenGera** [comment]
> After some testing I still have the issue and any of the oneblock commands are console only commands for some reason.
> 
> EDIT:
> 
> After some testing and having a fresh install of superior and oneblock the issue isn't fixed what could cause that ? Do you mind if I could send you my configs for you to try ? And I'm on 1.18.2
> 
> EDIT #2:
> 
> The issue is caused by the default lang, if it's not set to en-US it won't work, if changing the lang it will juste delete every lang file from the oneblock module and copy and paste the lang file from the superior lang files.

Makes sense - I will look into it.

**Comment by OmerBenGera** [comment]
The issue was because the lang files matching the default ones of SSB were missing.
I added lang files (they are not translated) to the OneBlock module as well and it shouldn't happen anymore.
In order to get these files generated, you must delete the lang folder inside OneBlock's folder, or create them manually yourself.
