### ISSUE TITLE
Blocks from the oneblock are counting in the is level and /is blocks

### ISSUE THREAD

**Issue by LuluxClient** [BG-Software-LLC/SSB-OneBlock#34]
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-72 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 8f05a00 on HEAD)
You are on the latest version!
Previous version: git-Pufferfish-71 (MC: 1.18.2)

### Plugin's Version

1.11.0.693 superior
build 29 of OneBlock

### Describe the bug

When breaking the oneblock block the blocks spawned by it are counted in the is level, limits and /is blocks

https://gyazo.com/ee65b40a6bbb2becb1b52b92e158b6c6

### To Reproduce

Create an island and break the block and do /is blocks

### Additional Information

https://gyazo.com/ee65b40a6bbb2becb1b52b92e158b6c6

**Comment by OmerBenGera** [comment]
Not a bug.
Every block in the island will be counted, as well as oneblock.
