### ISSUE TITLE
Placeholders doesn't support to "LOCATION" option

### ISSUE THREAD

**Issue by LuluxClient** [BG-Software-LLC/SSB-OneBlock#35]
### Minecraft's Version

1.18.2

### Plugin's Version

Superior 1.11.0.693 dev build
OneBlock: build 29

### Describe the bug

When trying to add the location option to a oneblock placeholder it returns a blank message

### To Reproduce

Just do /papi parse me %superior_oneblock_location_phase_name% 

### Additional Information

Doesn't work for every oneblock placeholders.

**Comment by OmerBenGera** [comment]
> ### Minecraft's Version
> 1.18.2
> 
> ### Plugin's Version
> Superior 1.11.0.693 dev build OneBlock: build 29
> 
> ### Describe the bug
> When trying to add the location option to a oneblock placeholder it returns a blank message
> 
> ### To Reproduce
> Just do /papi parse me %superior_oneblock_location_phase_name%
> 
> ### Additional Information
> Doesn't work for every oneblock placeholders.

Try %superior_location_oneblock...%

**Comment by LuluxClient** [comment]
> 

Not working

**Comment by OmerBenGera** [comment]
Update SSB to latest dev build, it will be supported using `%superior_location_oneblock...% `
Also, update OneBlock as I pushed some critical bug fixes.
