### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by olivervincent** [BG-Software-LLC/SSB-OneBlock#36]
### Minecraft's Version

PaperSpigot 1.19

### Plugin's Version

Latest

### Describe the bug

https://pastebin.com/8PEZrWm6

### To Reproduce

.

**Comment by olivervincent** [comment]
I don't know if this have something to do with Island Worth is going in -(negative).
You can see here: https://i.imgur.com/4dE38LL.png

Even though all the /is counts are positive. It's almost like when you mine the OneBlock, it takes away worth every time, but doesn't add the worth when it spawns.

**Comment by OmerBenGera** [comment]
About the first issue - update the addon.
About the second one, I will look into it
