### ISSUE TITLE
Reset Phases

### ISSUE THREAD

**Issue by olivervincent** [BG-Software-LLC/SSB-OneBlock#37]
### Minecraft's Version

Paper 1.19

### Plugin's Version

Latest

### Describe the bug

Everytime you restart the server, it resets the oneblock phases, so you start at phase 1 again.

### To Reproduce

1

**Comment by OmerBenGera** [comment]
What version of OneBlock and SuperiorSkyblock are you using?

**Comment by olivervincent** [comment]
> What version of OneBlock and SuperiorSkyblock are you using?

SuperiorSkyblock2-1.11.0-b696.jar

SSBOneBlock-1.2.1-b30.jar

**Comment by OmerBenGera** [comment]
Update OneBlock to b33, let me know if it fixes the issue

**Comment by olivervincent** [comment]
Yep fixed.

>
