### ISSUE TITLE
COMMAND actions use SSB-OB command isn't effective

### ISSUE THREAD

**Issue by SAFEluren** [BG-Software-LLC/SSB-OneBlock#39]
### Minecraft's Version

 This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Plugin's Version

SuperiorSkyblock2 version 1.11.0

### Describe the bug

COMMAND actions use SSB-OB command isn't effective.

### To Reproduce

1.Create a new phase after end-phase
2.Setup it
```
{
  "name": "backplains",
  "next-upgrade-cooldown": 10,
  "actions": [
    {
      "actions": [
        {
          "action": "COMMAND",
          "execute": [
            "ssboneblock:oneblock setphase {player} 1"
          ]
        }
      ]
    }
  ]
}
```
3.Reach this phase on game
4.See CONSOLE,plugin issues an execution success messageand,but player phase has no change

### Additional Information

Config.yml - phase
```
phases:
  - 'plains-phase.json'
  - 'underground-phase.json'
  - 'snow-phase.json'
  - 'ocean-phase.json'
  - 'jungle-phase.json'
  - 'red-desert-phase.json'
  - 'nether-phase.json'
  - 'idyll-phase.json'
  - 'desolate-phase.json'
  - 'end-phase.json'
  - 'go-plains.json'
```

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
