### ISSUE TITLE
Very high tick

### ISSUE THREAD

**Issue by Chan-log** [BG-Software-LLC/SSB-OneBlock#42]
### Minecraft's Version

1.19

### Plugin's Version

SSBOneBlock-1.2.1-b33

### Describe the bug

There is a lot of calculation when break a block

### To Reproduce

oneblock break

### Additional Information

https://spark.lucko.me/ZAHHq7rAZf

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it's better.

**Comment by OmerBenGera** [comment]
Have you tried it?

**Comment by OmerBenGera** [comment]
Closing this as it should be fixed.
If it still has issues, let me know
