### ISSUE TITLE
Chunk with generator disappeared

### ISSUE THREAD

**Issue by Doggy7331** [BG-Software-LLC/SSB-OneBlock#47]
### Minecraft's Version

PaperSpigot 1.18.2

### Plugin's Version

2022.8

### Describe the bug

Sometimes when someone leaves the island, a chunk with the generator disappears (Of course generator too). 
However, when the player put a block in the place where the generator was - it returns to it's place, but the rest of disapeared part of island doesn't.

### To Reproduce

I'm not exactly sure, but my players are saying that after leaving the server or only their island, sometimes when they're back, the whole island is like it was except to a chunk with generator which disappeared.

### Additional Information

[config.txt](https://github.com/BG-Software-LLC/SSB-OneBlock/files/9611089/config.txt)

**Comment by OmerBenGera** [comment]
Any errors in console?

**Comment by OmerBenGera** [comment]
Any errors in console?

**Comment by Doggy7331** [comment]
> Any errors in console?

No, there are no errors in the console

**Comment by Doggy7331** [comment]
> Any errors in console?

So, what's the solution of this problem?

**Comment by OmerBenGera** [comment]
Check out latest build of SSB, let me know if it works.

**Comment by OmerBenGera** [comment]
Closing this as it should be fixed.
If it still occurs, let me know by replying here.
