### ISSUE TITLE
overload problem

### ISSUE THREAD

**Issue by RangFarm** [BG-Software-LLC/SSB-OneBlock#49]
### Minecraft's Version

1.19.2

### Plugin's Version

SuperiorSkyblock2 - SuperiorSkyblock2-2022.9-b899
Oneblock modules - SSBOneBlock-1.2.1-b42

### Describe the bug

MSPT is becoming more and more difficult when there are 25 to 30 users of the one-block system.

### To Reproduce

MSPT is becoming more and more difficult when there are 25 to 30 users of the one-block system.

### Additional Information

Timings - https://timings.aikar.co/dev/?id=dc6efebec82644769821b04969c7292b
Spark - https://spark.lucko.me/GzK0cDA4Hw

**Comment by OmerBenGera** [comment]
Check out latest dev build (of oneblock), let me know if it's better.

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue persists, let me know.
