### ISSUE TITLE
Loop phases for the oneblock

### ISSUE THREAD

**Issue by iSeitan** [BG-Software-LLC/SSB-OneBlock#50]
### Minecraft's Version

The loop function doesnt seem to work, is that intented?

### Plugin's Version

The loop function doesnt seem to work, is that intented?

### Describe the bug

The loop function doesnt seem to work, is that intented?

### To Reproduce

The loop function doesnt seem to work, is that intented?

**Comment by OmerBenGera** [comment]
You can set the last phase to put the player in the first phase by making it execute `/ob setphase` and `/ob setphaseblock`.
This is not a bug.
