### ISSUE TITLE
bugged holograms

### ISSUE THREAD

**Issue by dan28000** [BG-Software-LLC/SSB-OneBlock#51]
### Minecraft's Version

1.19.2

### Plugin's Version

latest dev build of SSB b925 and latest dev build of OB addon

### Describe the bug

when trying to use multiple lines of text for timer hologram this happens both lines stacked on top of each other
![image](https://user-images.githubusercontent.com/84990628/206220369-7bf58673-a897-48c8-a3ea-3bbab5a7efb1.png)

few other pics and tries
as list it turn info string ![image](https://user-images.githubusercontent.com/84990628/206222697-30d3a4db-e1db-4140-9eca-9b75d4e1b68f.png)

using \n or /n nothing sill one line

the image on top
![image](https://user-images.githubusercontent.com/84990628/206222953-c368759e-9e90-42cc-bca8-487a831d98e5.png)

### To Reproduce

add multiple lines of text to the timer

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by dan28000** [comment]
still same issue
![image](https://user-images.githubusercontent.com/84990628/206723179-27001eaa-b260-4628-b76c-14f081a9463c.png)

**Comment by dan28000** [comment]
after quick look this is missing
![image](https://user-images.githubusercontent.com/84990628/208314786-e2445dd1-628e-42ca-9bf4-14cf3ef33190.png)

**Comment by OmerBenGera** [comment]
You were right, I forgot to increase the counter
Fixed in latest dev build
