### ISSUE TITLE
Issue with the phases block, container, possibility not recognised on latest

### ISSUE THREAD

**Issue by iSeitan** [BG-Software-LLC/SSB-OneBlock#53]
### Minecraft's Version

paper-1.19.3-338

### Plugin's Version

SSBOneBlock-1.2.1-b47
SuperiorSkyblock2-2022.9-b935

### Describe the bug

since this updates i've got this weird message in console spamming 19999999+ lines each reload and resert for every phases i got, any idea why?
[18:06:48 INFO]: [SuperiorSkyblock2-OneBlock] [end-blocks.json] Missing "container" section.
[18:06:48 INFO]: [SuperiorSkyblock2-OneBlock] [end-phase.json] Missing "offset" section.
Im looking at the json files, but i didnt change much i just added in each phases

    {
      "action": "command",
          "execute": [
            "island admin msgall {player} &6 ",
            "island admin msgall {player} &6 ",
            "island admin msgall {player} &6 Bravo vous avez fini la phase plaine...",
            "island admin msgall {player} &6 Voici 1,000$ et un cristal de netherite!",
            "island admin msgall {player} &6 ",
            "island admin msgall {player} &6 ",
            "money give %player% 1000",
            "ecoarmor give %player% crystal:netherite 1"
          ]
    }

Here's an example of my complete phases (each phases is built in the same format) https://pastebin.com/W4GPuTwv
Do you think my action command is not in the right place? 

I reseted the files, it still does the same, might be a plugin error :/
here's the latest log

### To Reproduce

Install a fresh version, and open the server

### Additional Information

latest log
[latest.log](https://github.com/BG-Software-LLC/SSB-OneBlock/files/10247767/latest.log)

**Comment by iSeitan** [comment]
Refreshed the full oneblock file and it does the same, its definitely a problem with the latest update of the oneblock module :)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build, sorry about that
