### ISSUE TITLE
Holograms disapearing after chunk unload

### ISSUE THREAD

**Issue by dan28000** [BG-Software-LLC/SSB-OneBlock#54]
### Minecraft's Version

purpur - 1858 1.19.2

### Plugin's Version

latest dev build for both superior and oneblock

superior - b951
ob - b51

### Describe the bug

get to a timer in ob phase works fine go to a different world and come back after bit of time now timer isn't showing anymore

### To Reproduce

set next-upgrade-cooldown to something high like 200 can be anything get to end of phase timer shows up find go to a different world for 10s and go back to your island and timer isn't showing anymore

### Additional Information

default set CMI

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
