### ISSUE TITLE
[HUGE DUPE BUG]

### ISSUE THREAD

**Issue by iSeitan** [BG-Software-LLC/SSB-OneBlock#55]
### Minecraft's Version

paper-1.19.3-379

### Plugin's Version

SuperiorSkyblock2-2022.9-b960
SSBOneBlock-1.2.1-b52

### Describe the bug

When the end of phases is a chest
the player can put stuff in the chest, then break the chest, then the same chest with the same new item respawn with the new stuff inside basically duping the stuff twice

### To Reproduce

go at the last phase block, mine it to have the end phase chest, put stuff inside, break it, then you'll have a second end phase chest with the dupe stuff
![2023-01-21_09 40 27](https://user-images.githubusercontent.com/86061857/213871962-dd50df8d-3662-4369-bff1-73cb5d28b3ae.png)
![2023-01-21_09 40 39](https://user-images.githubusercontent.com/86061857/213871966-9870c03d-67d7-4845-9932-0128c385d6a0.png)
![2023-01-21_09 40 43](https://user-images.githubusercontent.com/86061857/213871972-0997cc17-2816-4d1a-b0cc-dbf5fc490602.png)

**Comment by iSeitan** [comment]
I didnt test if that did the same for all chest while doing the phase, but since its a setblock too it might..

**Comment by iSeitan** [comment]
Many people did that yesterday on my server, so this might be a known bug in oneblock superiorskyblock2 and random user are trying it on server using this plugin

**Comment by OmerBenGera** [comment]
For now disable the chests I guess
I will only be able to look into it next week.
PRs are welcomed.

**Comment by iSeitan** [comment]
Yeah thats what I did, thanks!

**Comment by iSeitan** [comment]
So i removed the chest, so player cant dupe item

But i think the bug goes deeper, it seem that the last block of any phase when broke, respawn exactly the same (wich is why we could dupe)

So my question is, probably that with piston or any other minecraft mean, a player could replace the last phase block with any block like a diamond or nethertire block, break it, so the next block would be the same and then dupe the block?

**Comment by iSeitan** [comment]
Or with itemframe containing rare item

**Comment by iSeitan** [comment]
https://youtu.be/YuqeIIPVGzc

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue
I tried moving the oneblock in its last phase upwards as you shown in the video, then broke the other block and it seems to work fine - bedrock is placed.

**Comment by iSeitan** [comment]
Even with the chests?
Maybe I should give you my config?

**Comment by OmerBenGera** [comment]
> Even with the chests? Maybe I should give you my config?

It is not possible to move chests using pistons so I am really not sure how you did it with chests.

**Comment by iSeitan** [comment]
Oh the chests its not even linked to the piston
You could just drop stuff in the chest, then break the chest and the chest respawn with the stuff inside so it duped it

**Comment by iSeitan** [comment]
Doesnt happen with the default file, but if you put a setblock in the files it will create the block

**Comment by OmerBenGera** [comment]
The issue is because your last action does not have a setblock action, making the module being confused and it justs replaces the last block it set. Solution for this would be to combine your last two actions into one as follows:
```json
    {
      "actions": [
        {
          "action": "set_block",
         ...
        },
        {
          "action": "command",
          ...
        }
      ]
    }
```
