### ISSUE TITLE
Issues with oneblock and drop editor plugins 

### ISSUE THREAD

**Issue by Kristopherrr** [BG-Software-LLC/SSB-OneBlock#56]
### Minecraft's Version

This server is running Paper version git-Paper-359 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 3331501)
You are 25 version(s) behind

### Plugin's Version

Superior Skyblock2 2022.9-b964
Oneblock build 52

### Describe the bug

When you have a drop editor plugin ( Roseloot ), which edits any possible vanilla drop, the one block will keep dropping items even tho it shouldnt
![Screenshot_8](https://user-images.githubusercontent.com/114158743/214514500-7a28ea73-173c-42d5-8862-b917ab8df200.png)

### To Reproduce

1) Make a loottable from Roseloot with any of the blocks(dirt,glass,melon) anything would work
2) Make sure to be in survival mode
3) It will both drop the lootable from roseloot and the oneblock

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by Kristopherrr** [comment]
It doesn't seem to be fixed with the latest dev build 
![Screenshot_9](https://user-images.githubusercontent.com/114158743/215072705-0ee71a8d-b616-4c27-8f6f-4fcf2caab3a1.png)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works now

**Comment by Kristopherrr** [comment]
yeap now it's fixed. can i also request integration for this plugin? so the chests can have custom items in them? 
https://www.spigotmc.org/resources/%E2%9A%94%EF%B8%8F-executableitems-%E2%AD%90-custom-tools-weapons-armor-set-potions-mmo-items-vouchers-cosmetics-%E2%AD%90.83070/
![Screenshot_10](https://user-images.githubusercontent.com/114158743/215133704-0ac4f734-8a09-42f2-82e6-1392e111b162.png)

**Comment by OmerBenGera** [comment]
Closing this :)
About your feature request, a PR for that would be amazing!
