### ISSUE TITLE
Oneblock placeholders r not working

### ISSUE THREAD

**Issue by DextralityNetwork** [BG-Software-LLC/SSB-OneBlock#57]
### Minecraft's Version

1.17.1

### Plugin's Version

[01:49:25 INFO]: SuperiorSkyblock2 version 2022.9
[01:49:25 INFO]: Feature packed Skyblock core.
[01:49:25 INFO]: Website: https://bg-software.com/
[01:49:25 INFO]: Author: Ome_R

### Describe the bug

Placeholder are in blank:
- %superior_oneblock_phase_name%

### To Reproduce

![image](https://user-images.githubusercontent.com/99357255/215235570-61acf9b3-f853-41e7-aebe-7dfe5bcd4527.png)
- /papi parse PLAYER %superior_oneblock_phase_name%

**Comment by OmerBenGera** [comment]
It works fine for me

**Comment by DextralityNetwork** [comment]
Still in blank
![image](https://user-images.githubusercontent.com/99357255/215277242-52a82af5-9ff0-49fb-ac26-a9c909cc6bc4.png)
also with last dev version of oneblock

**Comment by OmerBenGera** [comment]
Recreate your island, you might not have a oneblock in your island.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue continues let me know
