### ISSUE TITLE
Failed to parse phase PHASE.json:

### ISSUE THREAD

**Issue by DextralityNetwork** [BG-Software-LLC/SSB-OneBlock#58]
### Minecraft's Version

1.17.1

### Plugin's Version

2022.9-b967

### Describe the bug

Failed to parse phase Mesa.json
[06:18:15 WARN]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
[06:18:15 WARN]:        at com.bgsoftware.ssboneblock.actions.container.SetContainerAction.fromJson(SetContainerAction.java:44)
[06:18:15 WARN]:        at com.bgsoftware.ssboneblock.actions.SetBlockAction.<init>(SetBlockAction.java:34)
[06:18:15 WARN]:        at com.bgsoftware.ssboneblock.actions.SetBlockAction.fromJson(SetBlockAction.java:72)
[06:18:15 WARN]:        at com.bgsoftware.ssboneblock.utils.JsonUtils.getAction(JsonUtils.java:54)
[06:18:15 WARN]:        at com.bgsoftware.ssboneblock.utils.JsonUtils.getActionSafely(JsonUtils.java:114)
[06:18:15 WARN]:        at com.bgsoftware.ssboneblock.utils.JsonUtils.getActionsArray(JsonUtils.java:87)
[06:18:15 WARN]:        at com.bgsoftware.ssboneblock.phases.PhaseData.fromJson(PhaseData.java:45)
[06:18:15 WARN]:        at com.bgsoftware.ssboneblock.handler.PhasesHandler.loadData(PhasesHandler.java:227)
[06:18:15 WARN]:        at com.bgsoftware.ssboneblock.handler.PhasesHandler.<init>(PhasesHandler.java:39)
[06:18:15 WARN]:        at com.bgsoftware.ssboneblock.OneBlockModule.onReload(OneBlockModule.java:80)
[06:18:15 WARN]:        at com.bgsoftware.ssboneblock.commands.commands.CmdReload.lambda$perform$0(CmdReload.java:49)
[06:18:15 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[06:18:15 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[06:18:15 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[06:18:15 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[06:18:15 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[06:18:15 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### To Reproduce

{
  "next-upgrade-cooldown": 180,
  "actions": [
    {
      "action": "set_block",
      "block": "terracotta",
      "amount": 3
    },
    {
      "actions": [
        {
          "action": "set_block",
          "block": "red_sandstone"
        },
        {
          "action": "command",
          "execute": [
            "is admin title {player} 40 80 12 -title &8[ &6■ &8] &6&lMesa &8• -subtitle &6❖ &fPaisaje variado por terracota &f●",
            "island admin msgall {player} &6 ",
            "island admin msgall {player} &6 ",
            "island admin msgall {player} &6 Has llegado a la fase 18: Mesa",
            "island admin msgall {player} &e El desierto es un lugar hostil de calor, polvo y muerte.",
            "island admin msgall {player} &6 ",
            "island admin msgall {player} &6 "
          ]
        }
      ]
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 7
    },
    {
      "action": "set_block",
      "block": "white_terracotta"
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "light_gray_terracotta",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "gold_ore",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 8
    },
    {
      "action": "set_block",
      "block": "light_gray_terracotta",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "gray_terracotta",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "copper_ore",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "orange_terracotta",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "coal_ore",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "cactus",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 7
    },
    {
      "actions": [
        {
          "action": "spawn_entity",
          "type": "villager"
        },
        {
          "action": "set_block",
          "block": "coal_ore"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 7
    },
    {
      "action": "random",
      "possibilities": "red-desert-blocks.json",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "lapis_ore",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "copper_ore",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "diamond_ore"
    },
    {
      "action": "set_block",
      "block": "clay",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "terracotta",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "dirt",
      "amount": 3
    },
    {
      "actions": [
        {
          "action": "spawn_entity",
          "type": "husk"
        },
        {
          "action": "set_block",
          "block": "white_terracotta"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "white_terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "yellow_terracotta",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "terracotta",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "yellow_terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "coal_ore",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "emerald_ore"
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 7
    },
    {
      "action": "set_block",
      "block": "gold_ore",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 4
    },
    {
      "actions": [
        {
          "action": "spawn_entity",
          "type": "wandering_trader"
        },
        {
          "action": "set_block",
          "block": "terracotta"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "clay",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "coal_ore",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "chest",
      "container": {
        "min": 2,
        "max": 4,
        "contents": "red-desert-chests.json"
      }
    },
    {
      "action": "set_block",
      "block": "yellow_terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 11
    },
    {
      "actions": [
        {
          "action": "spawn_entity",
          "type": "llama"
        },
        {
          "action": "set_block",
          "block": "red_sandstone"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "cactus",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "white_terracotta"
    },
    {
      "action": "set_block",
      "block": "orange_terracotta",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "hay_block",
      "amount": 3
    },
    {
      "action": "random",
      "possibilities": "red-desert-blocks.json",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "gold_ore",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "hay_block",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "red_sandstone",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "white_terracotta",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "iron_ore",
      "amount": 3
    },
    {
      "actions": [
        {
          "action": "spawn_entity",
          "type": "pillager"
        },
        {
          "action": "set_block",
          "block": "clay"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "clay",
      "amount": 4
    },
    {
      "action": "random",
      "possibilities": "red-desert-blocks.json",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "redstone_ore",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_terracotta",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 7
    },
    {
      "action": "set_block",
      "block": "copper_ore",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 5
    },
    {
      "actions": [
        {
          "action": "spawn_entity",
          "type": "vindicator"
        },
        {
          "action": "set_block",
          "block": "hay_block"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "hay_block",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "white_terracotta"
    },
    {
      "action": "set_block",
      "block": "brown_terracotta",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "dirt",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "emerald_ore",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "redstone_ore",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "gold_ore",
      "amount": 3
    },
    {
      "actions": [
        {
          "action": "spawn_entity",
          "type": "donkey"
        },
        {
          "action": "set_block",
          "block": "red_sandstone"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "white_terracotta",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "terracotta",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "chest",
      "container": {
        "min": 2,
        "max": 4,
        "contents": "red-desert-chests.json"
      }
    },
    {
      "action": "set_block",
      "block": "white_terracotta",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "red_sandstone",
      "amount": 6
    },
    {
      "action": "set_block",
      "block": "emerald_ore",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "chest",
      "container": {
        "min": 2,
        "max": 4,
        "contents": "superchest.json"
      }
    },
    {
      "action": "set_block",
      "block": "red_sandstone"
    },
    {
      "action": "set_block",
      "block": "white_terracotta",
      "amount": 3
    },
    {
      "action": "random",
      "possibilities": "red-desert-blocks.json",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "brown_terracotta",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "hay_block"
    },
    {
      "action": "set_block",
      "block": "diamond_ore",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "copper_ore",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "brown_terracotta"
    },
    {
      "action": "set_block",
      "block": "red_terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 2
    },
    {
      "actions": [
        {
          "action": "random",
          "possibilities": "red-desert-mobs.json"
        },
        {
          "action": "set_block",
          "block": "coal_ore"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "gold_ore",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "coal_ore",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "dirt",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "white_terracotta",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "white_terracotta"
    },
    {
      "action": "set_block",
      "block": "white_terracotta",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "hay_block",
      "amount": 2
    },
    {
      "action": "random",
      "possibilities": "red-desert-blocks.json",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 3
    },
    {
      "actions": [
        {
          "action": "random",
          "possibilities": "red-desert-mobs.json"
        },
        {
          "action": "set_block",
          "block": "iron_ore"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "iron_ore",
      "amount": 4
    },
    {
      "action": "random",
      "possibilities": "red-desert-blocks.json",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "lapis_ore"
    },
    {
      "action": "set_block",
      "block": "terracotta",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 8
    },
    {
      "action": "set_block",
      "block": "red_sandstone",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "chest",
      "container": {
        "min": 2,
        "max": 4,
        "contents": "red-desert-chests.json"
      }
    },
    {
      "action": "set_block",
      "block": "emerald_ore",
      "amount": 3
    },
    {
      "actions": [
        {
          "action": "random",
          "possibilities": "red-desert-mobs.json"
        },
        {
          "action": "set_block",
          "block": "coal_ore"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "coal_ore"
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "copper_ore",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "clay",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "yellow_terracotta",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "diamond_ore"
    },
    {
      "action": "set_block",
      "block": "red_terracotta",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "white_terracotta"
    },
    {
      "action": "random",
      "possibilities": "red-desert-blocks.json",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "gold_ore",
      "amount": 3
    },
    {
      "actions": [
        {
          "action": "random",
          "possibilities": "red-desert-mobs.json"
        },
        {
          "action": "set_block",
          "block": "emerald_ore"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "lapis_ore",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "redstone_ore",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "red_terracotta",
      "amount": 4
    },
    {
      "action": "random",
      "possibilities": "red-desert-blocks.json",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "brown_terracotta"
    },
    {
      "action": "set_block",
      "block": "terracotta",
      "amount": 9
    },
    {
      "actions": [
        {
          "action": "random",
          "possibilities": "red-desert-mobs.json"
        },
        {
          "action": "random",
          "possibilities": "red-desert-blocks.json"
        }
      ]
    },
    {
      "action": "random",
      "possibilities": "red-desert-blocks.json",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "dirt",
      "amount": 9
    },
    {
      "action": "set_block",
      "block": "white_terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 8
    },
    {
      "actions": [
        {
          "action": "random",
          "possibilities": "red-desert-mobs.json"
        },
        {
          "action": "random",
          "possibilities": "red-desert-blocks.json"
        }
      ]
    },
    {
      "action": "random",
      "possibilities": "red-desert-blocks.json",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "lapis_ore"
    },
    {
      "action": "set_block",
      "block": "clay"
    },
    {
      "action": "set_block",
      "block": "yellow_terracotta",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "chest",
      "container": {
        "min": 2,
        "max": 4,
        "contents": "red-desert-chests.json"
      }
    },
    {
      "action": "set_block",
      "block": "gold_ore",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "red_sandstone",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "redstone_ore",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "orange_terracotta",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "red_sandstone",
      "amount": 5
    },
    {
      "actions": [
        {
          "action": "random",
          "possibilities": "red-desert-mobs.json"
        },
        {
          "action": "set_block",
          "block": "cactus"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "cactus"
    },
    {
      "action": "set_block",
      "block": "chest",
      "container": {
        "min": 2,
        "max": 4,
        "contents": "superchest.json"
      }
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 2
    },
    {
      "action": "random",
      "possibilities": "red-desert-blocks.json",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "white_terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "red_terracotta"
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "cactus",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "red_sandstone",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "redstone_ore",
      "amount": 2
    },
    {
      "actions": [
        {
          "action": "random",
          "possibilities": "red-desert-mobs.json"
        },
        {
          "action": "set_block",
          "block": "redstone_ore"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "redstone_ore"
    },
    {
      "action": "set_block",
      "block": "white_terracotta"
    },
    {
      "action": "set_block",
      "block": "cactus",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "terracotta"
    },
    {
      "action": "set_block",
      "block": "red_sandstone",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "brown_terracotta",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "clay"
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 6
    },
    {
      "action": "set_block",
      "block": "terracotta"
    },
    {
      "action": "random",
      "possibilities": "red-desert-blocks.json",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "gold_ore",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "clay",
      "amount": 3
    },
    {
      "actions": [
        {
          "action": "random",
          "possibilities": "red-desert-mobs.json"
        },
        {
          "action": "set_block",
          "block": "white_terracotta"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "cactus",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "copper_ore",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand"
    },
    {
      "action": "set_block",
      "block": "red_sandstone",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "chest",
      "container": {
        "min": 2,
        "max": 4,
        "contents": "red-desert-chests.json"
      }
    },
    {
      "action": "random",
      "possibilities": "red-desert-blocks.json"
    },
    {
      "action": "set_block",
      "block": "white_terracotta"
    },
    {
      "action": "set_block",
      "block": "terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "iron_ore",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "emerald_ore",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "orange_terracotta"
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 5
    },
    {
      "actions": [
        {
          "action": "random",
          "possibilities": "red-desert-mobs.json"
        },
        {
          "action": "set_block",
          "block": "red_sandstone"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "copper_ore",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "redstone_ore",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "iron_ore"
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "orange_terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "orange_terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 8
    },
    {
      "actions": [
        {
          "action": "random",
          "possibilities": "red-desert-mobs.json"
        },
        {
          "action": "set_block",
          "block": "red_sandstone"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "clay",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "gold_ore",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "red_sandstone",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 8
    },
    {
      "action": "set_block",
      "block": "light_gray_terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "light_gray_terracotta",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 3
    },
    {
      "actions": [
        {
          "action": "random",
          "possibilities": "red-desert-mobs.json"
        },
        {
          "action": "set_block",
          "block": "brown_terracotta"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 7
    },
    {
      "action": "set_block",
      "block": "redstone_ore"
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "chest",
      "container": {
        "min": 2,
        "max": 4,
        "contents": "red-desert-chests.json"
      }
    },
    {
      "action": "set_block",
      "block": "red_sandstone",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "light_gray_terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "white_terracotta",
      "amount": 5
    },
    {
      "actions": [
        {
          "action": "random",
          "possibilities": "red-desert-mobs.json"
        },
        {
          "action": "set_block",
          "block": "orange_terracotta"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "copper_ore",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "orange_terracotta"
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 6
    },
    {
      "action": "set_block",
      "block": "orange_terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "white_terracotta",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "chest",
      "container": {
        "min": 2,
        "max": 4,
        "contents": "superchest.json"
      }
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "light_gray_terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "light_gray_terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 5
    },
    {
      "actions": [
        {
          "action": "random",
          "possibilities": "red-desert-mobs.json"
        },
        {
          "action": "set_block",
          "block": "white_terracotta"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "gold_ore",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "gold_ore"
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sandstone",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "white_terracotta",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "redstone_ore"
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "light_gray_terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand"
    },
    {
      "action": "set_block",
      "block": "light_gray_terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 3
    },
    {
      "action": "random",
      "possibilities": "red-desert-blocks.json",
      "amount": 4
    },
    {
      "actions": [
        {
          "action": "random",
          "possibilities": "red-desert-mobs.json"
        },
        {
          "action": "set_block",
          "block": "red_sand"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "light_gray_terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand"
    },
    {
      "action": "set_block",
      "block": "light_gray_terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "gold_ore",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "coal_ore",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "copper_ore",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "terracotta",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "gold_ore"
    },
    {
      "action": "set_block",
      "block": "red_sandstone",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "chest",
      "container": {
        "min": 2,
        "max": 4,
        "contents": "red-desert-chests.json"
      }
    },
    {
      "action": "random",
      "possibilities": "red-desert-blocks.json",
      "amount": 5
    },
    {
      "actions": [
        {
          "action": "random",
          "possibilities": "red-desert-mobs.json"
        },
        {
          "action": "set_block",
          "block": "red_sand"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "orange_terracotta",
      "amount": 5
    },
    {
      "action": "set_block",
      "block": "redstone_ore"
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "light_gray_terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sandstone",
      "amount": 4
    },
    {
      "action": "random",
      "possibilities": "red-desert-blocks.json",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 4
    },
    {
      "actions": [
        {
          "action": "random",
          "possibilities": "red-desert-mobs.json"
        },
        {
          "action": "set_block",
          "block": "red_sandstone"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "orange_terracotta"
    },
    {
      "action": "set_block",
      "block": "gold_ore",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "white_terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 4
    },
    {
      "action": "set_block",
      "block": "copper_ore",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sandstone",
      "amount": 6
    },
    {
      "action": "set_block",
      "block": "white_terracotta",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 2
    },
    {
      "actions": [
        {
          "action": "random",
          "possibilities": "red-desert-mobs.json"
        },
        {
          "action": "set_block",
          "block": "red_sandstone"
        }
      ]
    },
    {
      "action": "set_block",
      "block": "red_sandstone",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "white_terracotta",
      "amount": 3
    },
    {
      "action": "set_block",
      "block": "stone",
      "amount": 2
    },
    {
      "action": "set_block",
      "block": "red_sand",
      "amount": 5
    },
    {
      "action": "random",
      "possibilities": "red-desert-blocks.json",
      "amount": 15
    },
    {
      "actions": [
        {
          "action": "random",
          "possibilities": "red-desert-mobs.json"
        },
        {
          "action": "random",
          "possibilities": "red-desert-blocks.json"
        }
      ]
    },
    {
      "action": "random",
      "possibilities": "red-desert-blocks.json",
      "amount": 9
    }
  ]
}

### Additional Information

![image](https://user-images.githubusercontent.com/99357255/217164206-82d192f8-232e-437d-8abc-731091d1c328.png)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works now

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue persists, let me know
