### ISSUE TITLE
Addon isn't working

### ISSUE THREAD

**Issue by LuluxClient** [BG-Software-LLC/SSB-OneBlock#6]
Hey after installing the addon I had to fix some issues with old mob names such as pig_zombie etc, after fixing them I wanted to try some stuff but when doing /ob or /is oneblock nothing shows up, here is my console output: https://pastebin.com/j7y3vXCX

Version: 1.17.1
Oneblock: SSBOneBlock-1.2.0-b6
Superior: SuperiorSkyblock2 version 1.8.4.501

**Comment by LuluxClient** [comment]
And I'm also using java 17

**Comment by OmerBenGera** [comment]
Try /oneblock, let me know if it works.

**Comment by LuluxClient** [comment]
> Try /oneblock, let me know if it works.

nop nothing shows up in chat

**Comment by LuluxClient** [comment]
but when doing /ob save I get an output

**Comment by OmerBenGera** [comment]
It works fine for me using latest OneBlock and latest SSB.

**Comment by LuluxClient** [comment]
> It works fine for me using latest OneBlock and latest SSB.

what's your java and server version .?

**Comment by LuluxClient** [comment]
And also what's in your addon folder & more so I can try and find the issue

**Comment by OmerBenGera** [comment]
Java 17 and only OneBlock is inside the modules folder.

**Comment by LuluxClient** [comment]
> Java 17 and only OneBlock is inside the modules folder.
> 
> 

Oh I'll try and remove the engine thing then.

**Comment by OmerBenGera** [comment]
> > Java 17 and only OneBlock is inside the modules folder.
> 
> Oh I'll try and remove the engine thing then.

If you use Java 17 it will re-appear. How is the engine related to the issue anyways?

**Comment by LuluxClient** [comment]
Because you just said you only had the one block addon in your addon folder
and I’m having trouble finding the cause of this issue, I’ll setup a dev
server with only superior and his depends and try and find  the issue.

**Comment by LuluxClient** [comment]
> > > Java 17 and only OneBlock is inside the modules folder.
> > 
> > 
> > Oh I'll try and remove the engine thing then.
> 
> If you use Java 17 it will re-appear. How is the engine related to the issue anyways?

Hey after deleting everything etc I found out the issue was coming from superiorskyblock since I wasn't using the latest (I was 2 updates away) after deleting the configs and worlds everything got fixed, currently investigating what could've cause this issue.

**Comment by OmerBenGera** [comment]
> > > > Java 17 and only OneBlock is inside the modules folder.
> > > 
> > > 
> > > Oh I'll try and remove the engine thing then.
> > 
> > 
> > If you use Java 17 it will re-appear. How is the engine related to the issue anyways?
> 
> Hey after deleting everything etc I found out the issue was coming from superiorskyblock since I wasn't using the latest (I was 2 updates away) after deleting the configs and worlds everything got fixed, currently investigating what could've cause this issue.

Weird. Let me know what causes it once you find it.

**Comment by LuluxClient** [comment]
> > > > > Java 17 and only OneBlock is inside the modules folder.
> > > > 
> > > > 
> > > > Oh I'll try and remove the engine thing then.
> > > 
> > > 
> > > If you use Java 17 it will re-appear. How is the engine related to the issue anyways?
> > 
> > 
> > Hey after deleting everything etc I found out the issue was coming from superiorskyblock since I wasn't using the latest (I was 2 updates away) after deleting the configs and worlds everything got fixed, currently investigating what could've cause this issue.
> 
> Weird. Let me know what causes it once you find it.

Couldn't find anything.

**Comment by OmerBenGera** [comment]
> > > > > > Java 17 and only OneBlock is inside the modules folder.
> > > > > 
> > > > > 
> > > > > Oh I'll try and remove the engine thing then.
> > > > 
> > > > 
> > > > If you use Java 17 it will re-appear. How is the engine related to the issue anyways?
> > > 
> > > 
> > > Hey after deleting everything etc I found out the issue was coming from superiorskyblock since I wasn't using the latest (I was 2 updates away) after deleting the configs and worlds everything got fixed, currently investigating what could've cause this issue.
> > 
> > 
> > Weird. Let me know what causes it once you find it.
> 
> Couldn't find anything.

So it works now?

**Comment by LuluxClient** [comment]
> > > > > > > Java 17 and only OneBlock is inside the modules folder.
> > > > > > 
> > > > > > 
> > > > > > Oh I'll try and remove the engine thing then.
> > > > > 
> > > > > 
> > > > > If you use Java 17 it will re-appear. How is the engine related to the issue anyways?
> > > > 
> > > > 
> > > > Hey after deleting everything etc I found out the issue was coming from superiorskyblock since I wasn't using the latest (I was 2 updates away) after deleting the configs and worlds everything got fixed, currently investigating what could've cause this issue.
> > > 
> > > 
> > > Weird. Let me know what causes it once you find it.
> > 
> > 
> > Couldn't find anything.
> 
> So it works now?

Yep it works but I have some bugs, should I create a new ticket or I can continue this one

**Comment by OmerBenGera** [comment]
> > > > > > > > Java 17 and only OneBlock is inside the modules folder.
> > > > > > > 
> > > > > > > 
> > > > > > > Oh I'll try and remove the engine thing then.
> > > > > > 
> > > > > > 
> > > > > > If you use Java 17 it will re-appear. How is the engine related to the issue anyways?
> > > > > 
> > > > > 
> > > > > Hey after deleting everything etc I found out the issue was coming from superiorskyblock since I wasn't using the latest (I was 2 updates away) after deleting the configs and worlds everything got fixed, currently investigating what could've cause this issue.
> > > > 
> > > > 
> > > > Weird. Let me know what causes it once you find it.
> > > 
> > > 
> > > Couldn't find anything.
> > 
> > 
> > So it works now?
> 
> Yep it works but I have some bugs, should I create a new ticket or I can continue this one

Open new issues. One per bug report :)
