### ISSUE TITLE
When mining the oneblock, it get stuck

### ISSUE THREAD

**Issue by iSeitan** [BG-Software-LLC/SSB-OneBlock#60]
### Minecraft's Version

paper-1.19.3-397

### Plugin's Version

SSBOneBlock-1.2.1-b56
SuperiorSkyblock2-2022.9-b972

### Describe the bug

When mining the OneBlock, the player often has to re click to break the block, because if they don’t the block stays stuck and won’t change

https://youtu.be/5ITEOD6qmus

Any idea on how to fix this?

### To Reproduce

https://youtu.be/5ITEOD6qmus

Any idea on how to fix this?

**Comment by OmerBenGera** [comment]
Not a bug, they break it too quickly and it takes time for the block to get generated again.

**Comment by OmerBenGera** [comment]
You are more than welcome to make a PR that fixes it.
