### ISSUE TITLE
Sticky piston works on the oneblock

### ISSUE THREAD

**Issue by iSeitan** [BG-Software-LLC/SSB-OneBlock#63]
### Minecraft's Version

paper-1.19.3-448

### Plugin's Version

SuperiorSkyblock2-2022.9-b977
SSBOneBlock-1.2.1-b57

### Describe the bug

Sticky piston can be used on the oneblock, and it does the same effect as mining it, but doesnt drop the block

### To Reproduce

sticky piston on the oneblock

### Additional Information

Make it so it doesnt move and change the progression

**Comment by OmerBenGera** [comment]
You can move oneblock blocks using regular pistons as well as sticky pistons.
Why do you want it to be blocked?

**Comment by iSeitan** [comment]
Everything is written in my bug report, piston shouldn’t have any effect on the OneBlock.
People are abusing it

**Comment by OmerBenGera** [comment]
> Everything is written in my bug report, piston shouldn’t have any effect on the OneBlock. People are abusing it

How do they abuse it?
Why wouldn't piston have effect on oneblock?

**Comment by iSeitan** [comment]
We talked about this and you patched the normal piston, people were duping blocks and making an automated OneBlock farm
Now they make automatic farm with the sticky piston that mine the OneBlock automatically

Defeats the whole purposed of the gamemode
You ask for me to open a bug issue I don’t get why you’re reluctant to fix it x)

**Comment by OmerBenGera** [comment]
I am looking at the code and I don't see anything related to pistons tbh.
I don't see a reason why would people not be able to move oneblock blocks using pistons - it's the same as breaking them.
What advantage do they gain by doing so?

**Comment by OmerBenGera** [comment]
I added the ability to disable piston interactions with the OneBlock.
It is now toggleable in the config file - look for the `piston-interaction` section.

Let me know if it fixes the issue.

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed.
If the issue persists let me know
