### ISSUE TITLE
1.19.4 problem

### ISSUE THREAD

**Issue by ZappySK** [BG-Software-LLC/SSB-OneBlock#64]
### Minecraft's Version

Paper 1.19.4

### Plugin's Version

SSBOneBlock-1.2.1-b57.jar

### Describe the bug

![image](https://user-images.githubusercontent.com/76651966/226051414-aefbc184-7a62-4cf9-b5c5-250114d237f5.png)

### To Reproduce

I updated server to 1.19.4 and this happened..

**Comment by OmerBenGera** [comment]
Added in latest dev build
