### ISSUE TITLE
MagmaFoundation and OneBlock

### ISSUE THREAD

**Issue by GizzaGander** [BG-Software-LLC/SSB-OneBlock#66]
### Minecraft's Version

1.12.2

### Plugin's Version

1.2.1

### Describe the bug

Crash

### To Reproduce

![magma](https://user-images.githubusercontent.com/8245345/227500067-a8ec7413-5894-460a-a928-415ac165a44c.png)

**Comment by OmerBenGera** [comment]
Not supported.
