### ISSUE TITLE
1.20.1 blocks make island have no safe blocks to teleport too with oneblock addon

### ISSUE THREAD

**Issue by PunkMagic** [BG-Software-LLC/SSB-OneBlock#68]
### Minecraft's Version

[1.20.1] Pufferfish version git-Pufferfish-15

### Plugin's Version

SuperiorSkyblock2-2023.2-b40
SSBOneBlock-2023.2-b44

### Describe the bug

When applying cherry_log (new 1.20 block) into the plains phase, the block spawns fine, without issue and you can continue through your phase.
If the player stops while the cherry log is the only block on the island, and teleports away from their island to go to /spawn for example, they are unable to get back, by typing /oneblock giving an error "It seems like this island has no safe blocks. Please contact a staff member"

If the player has a home set on that block, they can get back, and continue as normal. 
This could be all 1.20 blocks, ive only tested with the cherry_log

![oneblockissue](https://github.com/BG-Software-LLC/SSB-OneBlock/assets/76727028/2b43e2dc-4413-4795-90eb-87b9c70b04e0)

### To Reproduce

We implemented cherry_log into our plains phase, to test and make sure the new 1.20.1 blocks are working as normal with the oneblock addon.

The cherry_log spawns, and we can mine as normal, and continue through the phase. If we stop, while the cherry_log is the ONLY block on the island, and teleport away from the island, and attempt to return, with the /oneblock command it will give this error "It seems like this island has no safe blocks. Please contact a staff member"

Teleporting back, with a /home has no issues, and allows the player to continue as normal.

### Additional Information

https://streamable.com/w3hpri

**Comment by OmerBenGera** [comment]
If the island has no safe blocks left, the plugin will not teleport the player to his island and send this warning.
Players should not keep their island with no safe blocks.

**Comment by OmerBenGera** [comment]
> > If the island has no safe blocks left, the plugin will not teleport the player to his island and send this warning. Players should not keep their island with no safe blocks.
> 
> If we try to reproduce this with with a 1.19.4 block, this issue does not happen. Which leads me to believe there is some 1.20.1 compatibility issues going on here.

This probably has nothing related to that.
SSB checks if the block is safe by making sure there's a solid block - maybe that specific block is not considered solid (which if so, then it is a bug with Spigot)

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues, let me know
