### ISSUE TITLE
Restarting the server isn't saving phases

### ISSUE THREAD

**Issue by LuluxClient** [BG-Software-LLC/SSB-OneBlock#7]
When you restart the server and the phase is changing it won't save your current phase and restart from phase 1. Also the placeholder is glitched. https://gyazo.com/a598c7fca66e2deb81905224fac2238b

**Comment by OmerBenGera** [comment]
You said the module doesnt work in your other issue...
Now it works?

**Comment by LuluxClient** [comment]
> You said the module doesnt work in your other issue...
> 
> Now it works?

No what I said is 0 commands are working but the game mode is working well kinda

**Comment by LuluxClient** [comment]
Hey any updates on that ?

**Comment by OmerBenGera** [comment]
Check out latest version of SSB, let me know if it helps.

**Comment by OmerBenGera** [comment]
I tested it and it works fine for me.
Check if the data was saved to the database file of OneBlock.

**Comment by LuluxClient** [comment]
> I tested it and it works fine for me. Check if the data was saved to the database file of OneBlock.

It doesn't save the data in oneblock and I'm now getting this error: https://pastebin.com/5ciWKtxt

I'm going to try and reset everything and try again.

**Comment by LuluxClient** [comment]
Nop still not working and it's not saving.... I'll have to delete the whole SuperiorSkyblock folder

**Comment by LuluxClient** [comment]
> Nop still not working and it's not saving.... I'll have to delete the whole SuperiorSkyblock folder

After deleting everything nothing is getting saved in the database.json of the oneblock addon 
I'm on 1.17.1 and on Java 17

**Comment by LuluxClient** [comment]
Hey could you foward me your config to see if it's a config issue if it's fixed for you ?

**Comment by OmerBenGera** [comment]
> Hey could you foward me your config to see if it's a config issue if it's fixed for you ?

I am using default files, besides that I fixed all the incorrect entity names for the version.

**Comment by LuluxClient** [comment]
Hey latest build seems fixed except for the hologram still being glitched

**Comment by OmerBenGera** [comment]
> Hey latest build seems fixed except for the hologram still being glitched

Hmm weird.
I will look into it again

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue with the holograms.

**Comment by LuluxClient** [comment]
> I can't seem to replicate the issue with the holograms.

Tried on both latest SSB and Superior and now I can't even remove the bedrock block 
I'm getting this error when breaking the bedrock block: https://gyazo.com/5c3ec6aea0444113a3400f245d6d4004 

and here is what I see after the bedrock is no longer here: https://gyazo.com/53892377c7bbeddeb8d0bad25d4796cd

**Comment by OmerBenGera** [comment]
> > I can't seem to replicate the issue with the holograms.
> 
> Tried on both latest SSB and Superior and now I can't even remove the bedrock block I'm getting this error when breaking the bedrock block: https://gyazo.com/5c3ec6aea0444113a3400f245d6d4004
> 
> and here is what I see after the bedrock is no longer here: https://gyazo.com/53892377c7bbeddeb8d0bad25d4796cd

I will look into it.

**Comment by OmerBenGera** [comment]
Does it still occur?

**Comment by OmerBenGera** [comment]
Check out latest build, lmk if it works now

**Comment by OmerBenGera** [comment]
Closing this for now
If the issue still persists, lmk
