### ISSUE TITLE
OneBlock module placeholder

### ISSUE THREAD

**Issue by ZappySK** [BG-Software-LLC/SSB-OneBlock#70]
### Minecraft's Version

Pufferfish 1.20.1

### Plugin's Version

SuperiorSkyblock2 version 2023.2-b77

### Describe the bug

![image](https://github.com/BG-Software-LLC/SSB-OneBlock/assets/76651966/efa72b0f-c132-4e52-a0bf-61fcbdacc06a)

SSB2 have this feature to show output in placeholder by standing in island, so I am wondering to add this feature into oneblock module because I created hologram addon but in holograms are showing "players" statistic not the island one..

### To Reproduce

Add the same feature as in SSB2 with location to oneblock module placeholders

**Comment by ZappySK** [comment]
@OmerBenGera hey, sup?

**Comment by OmerBenGera** [comment]
The placeholders of the module should be supported by the `%superior_island_location_<placeholder>%` format.

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues, let me know
