### ISSUE TITLE
OneBlock

### ISSUE THREAD

**Issue by MrMati594** [BG-Software-LLC/SSB-OneBlock#71]
### Minecraft's Version

Current: git-Purpur-1985 (MC: 1.19.4)*
Previous: git-Paper-207 (MC: 1.20.2)

### Plugin's Version

2023.3-b100

### Describe the bug

After breaking the Oneblock block, it starts to change/random itself, I don't know what to call it.

### To Reproduce

I sent a video on discord where it is shown

**Comment by MrMati594** [comment]
I tried changing the dev version of both plugins and it still doesn't work

**Comment by Envqu** [comment]
I have same problem

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by MrMati594** [comment]
It's still the same bug

**Comment by MrMati594** [comment]
When I placed obsidian (Every block works) under a grass block, the blocks stopped randomizing

**Comment by OmerBenGera** [comment]
Take a video of the issue.

**Comment by MrMati594** [comment]
I made a schematic, and I saved it as normal, replaced it with the default one and created an island. Maybe I'm doing something wrong. The schematic is one block of grass. https://www.youtube.com/watch?v=cf45vhGBtkg

**Comment by MrMati594** [comment]
dev build #44 works

**Comment by TheWylot** [comment]
@OmerBenGera still happens

**Comment by EditChris** [comment]
Can confirm, it's happening to me in Build 45 too, OneBlock is basically unplayable right now.

**Comment by Kocimietka7192** [comment]
I have the same problem with b110 and b45 oneblock, with the standard configuration - after destroying the block randomly destroys the blocks (or actually changes the block) exactly as it is uvododicated in the video sent by the user above.

**Comment by Envqu** [comment]
Hello. When we can expect fix?

**Comment by CodeAsm** [comment]
does reverting this https://github.com/BG-Software-LLC/SSB-OneBlock/issues/73#issuecomment-1819412732 fix it?
i cant test the 44 build but if it worked there, maybe we can revert the bug ?

**Comment by TheWylot** [comment]
Actually there is a commit (development) which @OmerBenGera didnt push into Main, maybe try a build with it?

**Comment by CodeAsm** [comment]
> Actually there is a commit (development) which @OmerBenGera didnt push into Main, maybe try a build with it?

that one builds and works yes :smile: awesome.

**Comment by OmerBenGera** [comment]
I just tried replicating the issue again, and I cannot replicate it myself.
I am using latest version of OneBlock (b45), SuperiorSkyblock (b121) and Purpur (b1985)

Does it occur for you with default config files?

**Comment by EditChris** [comment]
Looks like it started happening in 1.20.2, at least that's the first time I got that problem myself. On older versions it works as expected.

**Comment by OmerBenGera** [comment]
> Looks like it started happening in 1.20.2, at least that's the first time I got that problem myself. On older versions it works as expected.

I cannot replicate it on 1.20.2 neither.
Using `This server is running Paper version git-Paper-263 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 487109f)`

**Comment by EditChris** [comment]
Just created a test server in Paper 1.20.2 (b318), SuperiorSkyblock (b123) and OneBlock (b45). All with the default configurations. The only settings I touched in that server is setting the EULA to true, and changing the server port.

**Comment by Kocimietka7192** [comment]
I confirm, it's the same at my place. 
If necessary, you will send the server configuration.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it fixes the issue (dev build 46)

**Comment by OmerBenGera** [comment]
> Ok, tested that new build with Build 129 of SuperiorSkyBlock2, and from what I've tested looks like it's finally fixed!
> 
> Could you explain what was happening?

Incorrectly detecting block physics which automatically caused the module to run the next action
It was technically fixed a long time ago, however I didn't notice that the CI/CD doesn't compile the dev branch so it was never published.

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed.
If the issue continues let me know
