### ISSUE TITLE
As soon as you switch to 1.20.4, Oneblock doesn't work anymore 

### ISSUE THREAD

**Issue by SonnenPingu** [BG-Software-LLC/SSB-OneBlock#74]
### Minecraft's Version

1.20.4 paper

### Plugin's Version

Not available because it doesn't work. 

### Describe the bug

Update paper to 1.20.4 and you can't use Oneblock anymore.
You can't build a dev build either, because there's a serious bug in the code. 

### To Reproduce

Update paper to 1.20.4

**Comment by OmerBenGera** [comment]
Check out latest dev build, it was added :)
