### ISSUE TITLE
Island get buggy skipping all phases with waterbucket

### ISSUE THREAD

**Issue by DextralityNetwork** [BG-Software-LLC/SSB-OneBlock#75]
### Minecraft's Version

Pufferfish 1.17.1

### Plugin's Version

SSBOneBlock-2023.3

### Describe the bug

When u place water in the oneblock, this get buggy and skip all phases.

### To Reproduce

put waterbucket in oneblock

https://cdn.discordapp.com/attachments/1000093530221457539/1200891221535633428/Untitled.mp4?ex=65c7d41a&is=65b55f1a&hm=4ffe4bc7b0ef948efe219dc521e56f5d8a031522dd137a8e2b787d20363491f0&

### Additional Information

in before versions this bug dont work, specifically SSBOneBlock-2023.2-b44.jar

**Comment by OmerBenGera** [comment]
I fixed a similar issue not long time ago
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still occurs, let me know
