### ISSUE TITLE
OneBlock behaving very weird, Not spawning directly, Dropping Items that aren't supposed to

### ISSUE THREAD

**Issue by galsever** [BG-Software-LLC/SSB-OneBlock#78]
### Minecraft's Version

1.20.1

### Plugin's Version

2023.2

### Describe the bug

When i break the oneBlock it doesn't immediately respawn rather a few ticks after. Additionally it drops Items it shouldn't

https://github.com/BG-Software-LLC/SSB-OneBlock/assets/136364956/3241353c-d562-4643-9560-465229d3eca5

### To Reproduce

I dont know how, lol. I think i'm the only one with the issue

### Additional Information

Add me on discord so that I can send you a longer clip! (xmg_mc)

**Comment by SrinoYt** [comment]
Is there a way I can turn off the delay?

**Comment by OmerBenGera** [comment]
As I told you on the ticket -
1) The delay cannot be removed (You can make a PR with the changes if you wish)
2) The custom drops are not related to OneBlock, but to another plugin.

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still occurs, let me know
