### ISSUE TITLE
Conflicting Command Resolution: Modifying /ob Access for Island Management

### ISSUE THREAD

**Issue by Tortoche** [BG-Software-LLC/SSB-OneBlock#80]
### Minecraft's Version

1.20.4

### Plugin's Version

latest 

### Describe the bug

Hello, I'm making this report because I have a problem I would like to make the command /ob to access my island but the problem is that the module already uses this command. and I would like to know if it would be possible to add in the confige of the module add a line to change the command of the module or directly change the command as /adminob and /adminoneblock.

### To Reproduce

/ob and /is

**Comment by OmerBenGera** [comment]
Update both the module and the plugin, let me know if it works.

**Comment by Tortoche** [comment]
It's alright It works
