### ISSUE TITLE
/is oneblock error

### ISSUE THREAD

**Issue by Grellim** [BG-Software-LLC/SSB-OneBlock#83]
### Minecraft's Version

1.20.4

### Plugin's Version

SuperiorSkyblock2-2024.1-b200 and module SSBOneBlock-2024.1-b52

### Describe the bug

When load /is onblock https://mcpaste.io/2e563095469dd0a2

### To Reproduce

Purpur 1.20.4 stable version, Plugin and module install. Use the /is oneblock command.

**Comment by OmerBenGera** [comment]
My guess is there was an error when loading OneBlock that you missed.
Please send me the entire session logs by uploading them to pastebin.

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still occurs, let me know
