### ISSUE TITLE
Dupe Bug with pistons

### ISSUE THREAD

**Issue by Krin37** [BG-Software-LLC/SSB-OneBlock#84]
### Minecraft's Version

Pufferfish version git-Pufferfish-47 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9d12215 on HEAD)

### Plugin's Version

2024.1

### Describe the bug

You can dupe any content in a shulker, if placed on the central block, with a piston or using a minion from the plugin Jets Minions.

### To Reproduce

- Place a Miner Minion in front of the oneblock
- Let it mine the block -> Central block gets bugged (disappears)
- Place a shulker with items where the oneblock should be
- Mine the block -> Items inside Shulker will be dropped, and a shulker with same items will drop too.

I discovered that you can bug the central block just with a piston:
- Place a piston to move the central block
- Place a lever or a button or whatever activate the piston
- Activate the piston
- Deactivate the piston -> Central block doesn't appear again
- Place a shulker with items inside
- Mine the shulker

### Additional Information

https://github.com/BG-Software-LLC/SSB-OneBlock/assets/83928076/cfca4133-9519-42a4-afe3-a8a594375a02

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue still occurs, let me know
