### ISSUE TITLE
Items are dropped in a weird way

### ISSUE THREAD

**Issue by LuluxClient** [BG-Software-LLC/SSB-OneBlock#9]
Hey I was wondering if oneblock could add support to rosestacker, for example when breaking a block rosestack is making it so it will drop in the center of where the block has been broken but the oneblock addon prevent rosestacker from working on the "oneblock". I used to use bentobox and they have a similar system.
With this issue sometimes players lose items and sometimes even a single diamond can change everything. 
Here is an example of the issue: https://gyazo.com/696ec52a55c89390fab28ce1d62c0c11

**Comment by OmerBenGera** [comment]
OneBlock spawns the item **above** the placed block, unlike RoseStacker which spawns items inside the block.
If it will be the same as RoseStacker, your item will glitch out into the void.
Therefore, the current system is better than RoseStacker's one and will be kept the same.

**Comment by LuluxClient** [comment]
> OneBlock spawns the item **above** the placed block, unlike RoseStacker which spawns items inside the block. If it will be the same as RoseStacker, your item will glitch out into the void. Therefore, the current system is better than RoseStacker's one and will be kept the same.

Oh that's good to know, would be cool to add a feature like rose but a modified version for the oneblock
