### ISSUE TITLE
DUPE BUG - SHULKER AND ONEBLOCK BLOCK

### ISSUE THREAD

**Issue by DextralityEarth** [BG-Software-LLC/SSB-OneBlock#90]
### Minecraft's Version

Paper 1.20.4

### Plugin's Version

![image](https://github.com/user-attachments/assets/8eac8c7c-882d-477b-ad3a-e5c202dcc5e0)
![image](https://github.com/user-attachments/assets/664ee105-09aa-417d-9d90-88fa8a39c8ef)

### Describe the bug

People can bug the oneblock, and after that put shulkers, and at the end the oneblock when it regenerates breaks the shulker and gives duplicate things.

### To Reproduce

Now place tnt near the oenblock, explode the oneblock with tnt, then the block is bugged, place a shulker and wait until it is unbugged.

**Comment by OmerBenGera** [comment]
I don't understand what you mean by "wait for it until it is unbugged"
I broke the shulker box and it didn't dupe.

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still occurs, let me know
