### ISSUE TITLE
OneBlock Countdown hologram glitches 

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/SSB-OneBlock#93]
### Minecraft's Version

1.21.1 paper #100

### Plugin's Version

2024.3-b330

oneblock version: 60

### Describe the bug

when there is a cooldown between phases - hologram with a countdown glitches a lot and makes multiple countdowns that stuck on each other and does not disappear until the server gets restart

![image](https://github.com/user-attachments/assets/65efc5eb-9844-4a51-8f96-1ef632dabefe)
![IMG_5645](https://github.com/user-attachments/assets/5882bb7d-637d-43e0-a88d-6bae03f647f5)

### To Reproduce

Finish OneBlock phase and get a cooldown hologram

**Comment by homerek111** [comment]
@OmerBenGera any chance of changing this holograms somehow?

**Comment by OmerBenGera** [comment]
I cant replicate it myself.
Are you able to replicate it on a server with only SSB and the OneBlock module?

**Comment by homerek111** [comment]
> I cant replicate it myself. Are you able to replicate it on a server with only SSB and the OneBlock module?

It does not happen with a single island - it happened on my server when there were many islands having phase cooldown at the same time

**Comment by OmerBenGera** [comment]
Check out latest dev build of the module, let me know if it still occurs

**Comment by homerek111** [comment]
> Check out latest dev build of the module, let me know if it still occurs

@OmerBenGera seems to be still happening
![2024-11-14_14 26 34](https://github.com/user-attachments/assets/fef41524-8c55-4608-a26c-6836ab5b8682)

**Comment by homerek111** [comment]
2024.3-b360
oneblock #67

**Comment by OmerBenGera** [comment]
How to replicate the issue?

**Comment by homerek111** [comment]
> How to replicate the issue?

no idea - just player reported me that -> i teleported there and thats what i see

**Comment by OmerBenGera** [comment]
> > How to replicate the issue?
> 
> no idea - just player reported me that -> i teleported there and thats what i see

Try replicating it yourself as well

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by homerek111** [comment]
> Any news regarding this?

Nope :/

**Comment by OmerBenGera** [comment]
Well you must try and replicate it, otherwise I can't do anything and will have to close this bug report.

**Comment by homerek111** [comment]
> Well you must try and replicate it, otherwise I can't do anything and will have to close this bug report.

At the moment edition of my oneblock server is over - I will re-open the issue if it occurs on the future edition.
