### ISSUE TITLE
[feature request] explosion protection for oneblock generator 

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/SSB-OneBlock#94]
### Minecraft's Version

-

### Plugin's Version

-

### Describe the bug

![IMG_5656](https://github.com/user-attachments/assets/2cdefbff-741d-4f43-9ba1-196c213f94d6)

### To Reproduce

-

**Comment by OmerBenGera** [comment]
Creeper/tnt explosion should also make the magic block go to the next phase. Is it not the case?

**Comment by homerek111** [comment]
> Creeper/tnt explosion should also make the magic block go to the next phase. Is it not the case?

After the explosion the generator breaks and it is not respawning again - you have to manually fix it by placing+breaking some block there

**Comment by homerek111** [comment]
> > Creeper/tnt explosion should also make the magic block go to the next phase. Is it not the case?
> 
> After the explosion the generator breaks and it is not respawning again - you have to manually fix it by placing+breaking some block there

@OmerBenGera what do you think about this issue :/

**Comment by OmerBenGera** [comment]
Check out latest dev build of the module, let me know if it is fixed

**Comment by homerek111** [comment]
> Check out latest dev build of the module, let me know if it is fixed

fixed, forgot to report

**Comment by OmerBenGera** [comment]
Great.
Closing this for now
