### ISSUE TITLE
null placeholder when leader is offline

### ISSUE THREAD

**Issue by m-surowiec** [BG-Software-LLC/SSB-OneBlock#95]
### Minecraft's Version

This server is running Paper version 1.21.1-100-master@20ec622 (2024-09-26T23:53:46Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugin's Version

2024.3-b341

### Describe the bug

When the leader is offline and I execute `/oneblock setphase mSuro_ 3` the phase doesn't update and if I try to send the `{player}` placeholder it returns `null` instead of the leader's name

### To Reproduce

Parse the {player} placeholder when leader is offline

### Additional Information

![Screenshot 2024-10-19 at 15 49 01](https://github.com/user-attachments/assets/ec8cf39e-ef61-4ce1-a01f-ea57054e1891)
`null` is the argument of a command executed with the placeholder

**Comment by homerek111** [comment]
@OmerBenGera i confirm this issue

**Comment by m-surowiec** [comment]
I think it's because you are parsing the leader as Player instead of OfflinePlayer even though I don't see that you are using any of methods from Player

**Comment by homerek111** [comment]
@OmerBenGera could you take a look at that?

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by m-surowiec** [comment]
It's fixed, thanks :)
